name: Deploy Angular App cafeteriaWeb

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: ng build --configuration production -- --base-href /cuina/

      - name: Copy files via SSH (port 35001)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 35001
          source: "dist/cafeteria-app-web/**"
          target: "/var/www/html/restauracio/cuina"
          strip_components: 2

      - name: Reload Apache (via SSH on port 35001)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 35001
          script: |
            sudo systemctl reload apache2
